/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getFileSystemInfo(dir: string | null) {
    return invoke()<FileSystemInfo>("get_file_system_info", { dir })
}

export function openFile(path: string, currentWorkingDirectory: string) {
    return invoke()<OpenFile>("open_file", { path,currentWorkingDirectory })
}

export function getSourceCodeIfAny(id: number) {
    return invoke()<string | null>("get_source_code_if_any", { id })
}

export function closeFile(id: number) {
    return invoke()<null>("close_file", { id })
}

export function saveFile(id: number, changes: string) {
    return invoke()<null>("save_file", { id,changes })
}

export function reset() {
    return invoke()<null>("reset")
}

export type FileSystemInfo = { current_directory: string; directory_items: DirectoryItem[] }
export type Lang = "Javascript" | "Typescript" | "Rust" | "Python" | "Java" | "Ruby" | "Html" | "Css"
export type OpenFile = { id: number; name: string; language: Lang | null; same_name_exist: boolean; path_relative_to_current_dir: string }
export type DirectoryItem = { is_file: boolean; name: string; path: string; childrens: DirectoryItem[] | null }
