/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getFileSystemInfo(dir: string | null) {
    return invoke()<FileSystemInfo>("get_file_system_info", { dir })
}

export function openFile(path: string) {
    return invoke()<OpenFile>("open_file", { path })
}

export function getFileInfo(id: number) {
    return invoke()<OpenedFile | null>("get_file_info", { id })
}

export type DirectoryItem = { is_file: boolean; name: string; path: string; item: DirectoryItem[] | null }
export type OpenFile = { id: number; name: string; language: Lang | null }
export type Lang = "Javascript" | "Typescript" | "Rust" | "Python" | "Java" | "Ruby" | "Html" | "Css"
export type FileSystemInfo = { current_directory: string; directory_items: DirectoryItem[] }
export type OpenedFile = { name: string; source_code: number[]; language: Lang | null }
